CREATE TABLE AuditLog (
   AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
   TransactionID NUMBER,
   AccountID NUMBER,
   Amount NUMBER,
   TransactionType VARCHAR2(20),
   LogDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
   INSERT INTO AuditLog(
      TransactionID,
      AccountID,
      Amount,
      TransactionType,
      LogDate
   )
   VALUES(
      :NEW.TransactionID,
      :NEW.AccountID,
      :NEW.Amount,
      :NEW.TransactionType,
      SYSDATE
   );
END;
INSERT INTO Transactions
VALUES(
3,
1,
SYSDATE,
500,
'Deposit'
);

SELECT * FROM AuditLog;